Repository babylonhealth/ios-playbook, pull requests merged in 2019-11, with the labels that each got.

#266 Update FastlaneMatch.md
  Cookbook/Technical-Documents/FastlaneMatch.md
Labels: Ready for Review 🚀

#194 [CNSMR-2053] Add Architecture.md
  Cookbook/README.md
  Cookbook/Technical-Documents/Architecture.md
Labels: Outline, Ready for Review 🚀

#267 Add implicit returns to styleguide
  Cookbook/Style-guide/README.md
Labels: Ready for Review 🚀

#213 Bento-as-SwiftUI manifesto
  Cookbook/Technical-Documents/Bento-SwiftUI-manifesto.md
Labels: Ready for Review 🚀

#268 Update SlackCIIntegration.md
  Cookbook/Technical-Documents/SlackCIIntegration.md
Labels: Ready for Review 🚀

#270 Add myself to the team
  Cookbook/Technical-Documents/NewHiresCheckList.md
  README.md
  scripts/squads.yml
Labels: Ready for Review 🚀

#272 Notify holidays in team calendar
  Cookbook/Technical-Documents/OutOffOfficeRequest.md
Labels: Ready for Review 🚀

#275 Update new hire checklist with Slack user groups
  Cookbook/Technical-Documents/NewHiresCheckList.md
Labels: Ready for Review 🚀, Trivial

#276 Change Ruby version instruction to 2.6.4
  Cookbook/Technical-Documents/NewHiresCheckList.md
Labels: Ready for Review 🚀

#277 Update meetings purpose document with new changes related to PR parties
  Cookbook/Technical-Documents/meetings-purpose.md
Labels: Ready for Review 🚀

#204 Create Feature Switches guide
  Cookbook/Technical-Documents/Assets/adding-remote-config-condition.png
  Cookbook/Technical-Documents/Assets/adding-remote-config-flag.png
  Cookbook/Technical-Documents/FeatureSwitches.md
Labels: Ready for Review 🚀

#185 [CNSMR-1852] Article: From 0% to 100% screen with Bento
  Cookbook/Technical-Documents/Assets/bento-image-01.png
  Cookbook/Technical-Documents/Assets/bento-image-02.png
  Cookbook/Technical-Documents/Assets/bento-image-03.png
  Cookbook/Technical-Documents/From_0%_to_100%_with_Bento.md
Labels: Ready for Review 🚀

#279 Adds a question to FUNCTIONAL REACTIVE PROGRAMMING (Interview)
  Interview/questions.md
Labels: Ready for Review 🚀

#283 Configure custom Xcode counterparts
  Cookbook/Technical-Documents/Assets/counterparts.png
  Cookbook/Technical-Documents/XcodeTips.md
Labels: Ready for Review 🚀

#284 Add more informations about Firebase feature switches
  Cookbook/Technical-Documents/FeatureSwitches.md
Labels: Ready for Review 🚀

#282 Update release documents
  Cookbook/Technical-Documents/ReleaseProcess.md
Labels: Ready for Review 🚀, Release 💥

#278 Tech Test - Change test scope
  Interview/demo.md
Labels: Proposal 🙈, Ready for Review 🚀

#291 Update FastlaneMatch.md
  Cookbook/Technical-Documents/FastlaneMatch.md
Labels: Ready for Review 🚀, Trivial

#285 Update SlackCIIntegration.md
  Cookbook/Technical-Documents/SlackCIIntegration.md
Labels: Ready for Review 🚀
