Repository babylonhealth/ios-playbook, pull requests merged in 2019-03, with the labels that each got.

#49 Lists the Slack relevant channels and apps
  README.md
Labels: Ready for Review 🚀

#51 Update on staffing numbers
  README.md
Labels: Ready for Review 🚀

#52 Add jira ticket for ForgotPasswordViewModel
  TechnicalDocuments/TechnicalDebt.md
Labels: Ready for Review 🚀

#22 Screen Lifecycle Observation...
  TechnicalDocuments/Proposals/ScreenLifecycleObservation.md
Labels: Proposal 🙈, Ready for Review 🚀

#47 Remove new hires checklists from frontpage
  README.md
  TechnicalDocuments/NewHiresCheckList.md
Labels: Ready for Review 🚀

#56 JIRA tickets for fixing some technical debt.
  TechnicalDocuments/TechnicalDebt.md
Labels: Ready for Review 🚀

#10 Switch to SnapshotTesting 📸
  TechnicalDocuments/README.md
  TechnicalDocuments/SnapshotTesting.md
Labels: Proposal 🙈, Ready for Review 🚀

#57 3.11.0 - Update release board
  release.md
Labels: Ready for Review 🚀, Release 💥

#61 Link accepted proposals properly.
  TechnicalDocuments/Proposals/SnapshotTesting.md
  TechnicalDocuments/README.md
Labels: Ready for Review 🚀

#63 Add public channels for squads (if there are any)
  README.md
Labels: Ready for Review 🚀

#64 This should be a requirement for our demo
  Interview/demo.md
Labels: Ready for Review 🚀

#65 [Interview] Add reloading requirement
  Interview/demo.md
Labels: Ready for Review 🚀

#66 Add question around how UIKit handles touch events
  Interview/questions.md
Labels: Ready for Review 🚀

#67 Added new OSS projects + Added Inami to Native Apps
  README.md
Labels: Ready for Review 🚀

#68 Added 3.12.0 to releases
  release.md
Labels: Ready for Review 🚀

#71 Add UIFlow, style guide mantainer
  README.md
Labels: Ready for Review 🚀

#73 Update new hires checklist
  TechnicalDocuments/NewHiresCheckList.md
Labels: Ready for Review 🚀

#62 13. Replace Builders with Free Functions
  TechnicalDocuments/Proposals/BuildersToFunctions.md
Labels: Proposal 🙈, Ready for Review 🚀
