Repository babylonhealth/ios-playbook, pull requests merged in 2019-09, with the labels that each got.

#205 Describe some Xcode keybindings
  Cookbook/Technical-Documents/Assets/cmd-ctrl-click-navigation.png
  Cookbook/Technical-Documents/Assets/floating-panel-navigation.png
  Cookbook/Technical-Documents/Assets/optional-navigation-tab.png
  Cookbook/Technical-Documents/Assets/test-navigator-attachments.png
  Cookbook/Technical-Documents/Assets/xcode-custom-behaviors.png
  Cookbook/Technical-Documents/XcodeTips.md
Labels: Ready for Review 🚀

#199 Managing Assets
  Cookbook/Proposals/ManagingAssets.md
Labels: Proposal 🙈, Ready for Review 🚀

#230 Technical exercise for the iOS Automation Engineer position
  Cookbook/README.md
  Interview/AutomationExercise.md
Labels: Proposal 🙈, Ready for Review 🚀

#231 Update squad vision.
  scripts/squads.yml
Labels: Ready for Review 🚀, Trivial

#208 Clarify what merge strategy we use to merge the release back into develop
  Cookbook/Technical-Documents/ReleaseProcess.md
Labels: Ready for Review 🚀

#200 [CNSMR-1812] Feature Switches redesign
  Cookbook/Proposals/FeatureSwitchesRedesign.md
Labels: Proposal 🙈, Ready for Review 🚀

#240 [CNSMR-2925] Add tutorial for accessing App Center builds
  Cookbook/README.md
  Cookbook/Technical-Documents/AppCenter.md
  Cookbook/Technical-Documents/Assets/app-center/company-or-school.png
  Cookbook/Technical-Documents/Assets/app-center/email.png
  Cookbook/Technical-Documents/Assets/app-center/iphone-profle-trust.png
  Cookbook/Technical-Documents/Assets/app-center/iphone-settings-general.png
  Cookbook/Technical-Documents/Assets/app-center/iphone-settings-profile-trust.png
  Cookbook/Technical-Documents/Assets/app-center/iphone-settings-profiles.png
  Cookbook/Technical-Documents/Assets/app-center/iphone-settings.png
  Cookbook/Technical-Documents/Assets/app-center/missing-device.jpg
  Cookbook/Technical-Documents/Assets/app-center/okta.png
  Cookbook/Technical-Documents/Assets/app-center/project-install.jpg
  Cookbook/Technical-Documents/Assets/app-center/project-list.png
  Cookbook/Technical-Documents/Assets/app-center/untrusted-developer.png
Labels: Ready for Review 🚀

#220 Add functional operators article
  Cookbook/README.md
  Cookbook/Technical-Documents/FunctionalOperators.md
Labels: Ready for Review 🚀

#241 Added bullet numbering for existing questions
  Interview/questions.md
Labels: Ready for Review 🚀

#244 Remove Jakub
  README.md
  scripts/squads.yml
Labels: Ready for Review 🚀, Trivial
