Repository babylonhealth/ios-playbook, pull requests merged in 2019-05, with the labels that each got.

#119 Style guide: encourage use of `MARK`s when they help improve code organisation
  Cookbook/Style-guide/README.md
Labels: Ready for Review 🚀

#60 Update to the SDK Release process
  Cookbook/Technical-Documents/ReleaseProcess.md
Labels: Ready for Review 🚀

#122 Update SnowplowHowTo.md
  Cookbook/Technical-Documents/SnowplowHowTo.md
Labels: Ready for Review 🚀

#123 Style guide: make it clear that the suggested max line length is 120
  Cookbook/Style-guide/README.md
  Cookbook/Technical-Documents/NewHiresCheckList.md
Labels: Ready for Review 🚀

#116 Update FastlaneMatch.md
  Cookbook/Technical-Documents/FastlaneMatch.md
Labels: Ready for Review 🚀

#110 [Proposal] Integrate Danger
  Cookbook/Proposals/Danger-Integration.md
Labels: Proposal 🙈, Ready for Review 🚀

#130 [CNSMR-1523] Add framework creation documentation
  Cookbook/Technical-Documents/AddingFrameworks.md
  Cookbook/Technical-Documents/Assets/Framework-settings-to-keep.png
  Cookbook/Technical-Documents/Assets/Framework-xcconfig.png
Labels: Ready for Review 🚀

#131 Adds Adrian Śliwa
  README.md
Labels: Ready for Review 🚀

#114 Added a guide on using Slack + CI integration
  Cookbook/README.md
  Cookbook/Technical-Documents/SlackCIIntegration.md
Labels: Ready for Review 🚀

#126 [StyleGuide] Add "Declaration Order"
  Cookbook/Style-guide/README.md
Labels: Ready for Review 🚀

#74 [Proposal] Top-priority member-variable and initializer declarations
  TechnicalDocuments/Proposals/TopPriorityMemberVariables.md
Labels: Proposal 🙈, Ready for Review 🚀

#133 Adds Nicola Di Pol
  README.md
Labels: Ready for Review 🚀

#134 Update the process around gathering release notes
  Cookbook/Technical-Documents/ReleaseProcess.md
Labels: Ready for Review 🚀

#135 New hires checklist: how to build and run on personal iOS devices
  Cookbook/Technical-Documents/NewHiresCheckList.md
Labels: Ready for Review 🚀

#106 [Proposal] Standardise Setup of Models in Tests
  Cookbook/Proposals/ModelFixtures.md
Labels: Proposal 🙈, Ready for Review 🚀

#102 [Proposal] Simple side-effect in ReactiveFeedback
  Cookbook/Proposals/SimpleSideEffectInReactiveFeedback.md
Labels: Proposal 🙈, Ready for Review 🚀

#121 Add some internal tools to the list
  Cookbook/Technical-Documents/ToolsAndServices.md
Labels: Ready for Review 🚀

#138 Update release document for 3.16.0
  Cookbook/Technical-Documents/ReleaseProcess.md
Labels: Ready for Review 🚀, Release 💥

#139 Add details about myself to the Readme
  README.md
Labels: Ready for Review 🚀

#111 Some typos and indentation fixes
  Cookbook/README.md
  Cookbook/Technical-Documents/AutomationIdentifiers.md
Labels: Ready for Review 🚀

#140 Hide the team id from the fastlane match documentation
  Cookbook/Technical-Documents/FastlaneMatch.md
Labels: Ready for Review 🚀

#124 Added more details to the Release Engineer Role
  Cookbook/Technical-Documents/ReleaseProcess.md
Labels: Ready for Review 🚀

#142 Update squad capacity in README.md
  README.md
Labels: Ready for Review 🚀

#141 Add link to AddingFrameworks.md to the Cookbook
  Cookbook/README.md
  Cookbook/Technical-Documents/AddingFrameworks.md
Labels: Ready for Review 🚀

#128 Add more details on the release engineers role
  Cookbook/Technical-Documents/ReleaseProcess.md
Labels: Ready for Review 🚀

#147 👶 Fix typo in AddingFrameworks.md
  Cookbook/Technical-Documents/AddingFrameworks.md
Labels: Ready for Review 🚀
