Repository babylonhealth/ios-playbook, pull requests merged in 2019-12, with the labels that each got.

#273 [CNSMR-3187] How to Work with Optimizely.
  Cookbook/README.md
  Cookbook/Technical-Documents/Assets/optimizely/OptimizelyExperimentActivations.png
  Cookbook/Technical-Documents/Assets/optimizely/OptimizelyProjects.png
  Cookbook/Technical-Documents/Optimizely.md
Labels: Ready for Review 🚀

#294 Update OOO steps for calendar event
  Cookbook/Technical-Documents/OutOffOfficeRequest.md
Labels: Ready for Review 🚀, Trivial

#295 Update release calendar with Babylon 4.12.0
  Cookbook/Technical-Documents/ReleaseProcess.md
Labels: Trivial

#293 [IOSP-389] Setting up RubyMine
  Cookbook/README.md
  Cookbook/Technical-Documents/Assets/RubyMineLicense.png
  Cookbook/Technical-Documents/Assets/RubyMinePreferences.png
  Cookbook/Technical-Documents/RubyMine.md
Labels: Ready for Review 🚀

#300 Update PR labels documention as per decision in the latest iOS retro
  Cookbook/Technical-Documents/LabelsInPRs.md
Labels: Ready for Review 🚀

#292 [CNSMR-3180] Proposal: Decouple snapshot tests from unit tests
  Cookbook/Proposals/DecoupleSnapshotTestsFromUnitTests.md
Labels: Proposal 🙈, Ready for Review 🚀

#303 [IOSP-453] Add VerticalFrameworks.md
  Cookbook/Technical-Documents/Assets/dependency-v4.12.0.png
  Cookbook/Technical-Documents/Assets/parallel-build.png
  Cookbook/Technical-Documents/VerticalFrameworks.md
Labels: Ready for Review 🚀

#304 [CNSMR-3226] - Application Distribution documentation
  Cookbook/Technical-Documents/ApplicationDistribution.md
Labels: Ready for Review 🚀

#289 [CNSMR-3203] Add task review guidelines
  Cookbook/Technical-Documents/TaskReviewGuidelines.md
Labels: Ready for Review 🚀

#305 Add document with snapshot testing tips
  Cookbook/README.md
  Cookbook/Technical-Documents/SnapshotTestingTips.md
Labels: Ready for Review 🚀
