Repository babylonhealth/ios-playbook, pull requests merged in 2019-01, with the labels that each got.

#17 Removed some irrelevant questions
  Interview/questions.md
Labels: Ready for Review 🚀

#23 Added column for relevant dates
  release.md
Labels: Ready for Review 🚀

#24 added the SDK distribution steps
  release.md
Labels: Ready for Review 🚀

#28 Code owners: Restoring developer's efficiency
  TechnicalDocuments/Proposals/CODEOWNERS.md
Labels: Proposal 🙈, Ready for Review 🚀

#27 Update data for `3.8.0` release
  release.md
Labels: Ready for Review 🚀, Release 💥
