Repository babylonhealth/ios-playbook, pull requests merged in 2019-06, with the labels that each got.

#146 Update ReleaseProcess: release 3.17.0
  Cookbook/Technical-Documents/ReleaseProcess.md
Labels: Release 💥

#144 Add documentation for Navigation Behaviours
  Cookbook/Technical-Documents/DesignLibrary.md
Labels: Ready for Review 🚀

#118 Style guide: add note about extension access qualifiers because of new SwiftLint rule.
  Cookbook/Style-guide/README.md
Labels: Ready for Review 🚀

#149 Firebase info added to tools & services table
  Cookbook/Technical-Documents/ToolsAndServices.md
Labels: Ready for Review 🚀

#148 Update the documentation style
  Cookbook/Technical-Documents/FastlaneMatch.md
Labels: Ready for Review 🚀

#112 [Proposal] Danger rule for xcodeproj
  Cookbook/Proposals/Danger-Rule-Xcodeproj.md
Labels: Proposal 🙈, Ready for Review 🚀

#150 👶Move proposals from the old dir to the new one
  .github/PULL_REQUEST_TEMPLATE/proposal.md
  Cookbook/Proposals/TopPriorityMemberVariables.md
Labels: Ready for Review 🚀

#155 Addressed some more review comments
  Cookbook/Technical-Documents/FastlaneMatch.md
Labels: Ready for Review 🚀

#157 Add Apple Pay documentation
  Cookbook/README.md
  Cookbook/Technical-Documents/Apple_Pay.md
Labels: Ready for Review 🚀

#156 Add DebugBuilder.md
  Cookbook/Technical-Documents/DebugBuilder.md
Labels: Ready for Review 🚀

#154 Document a naming convention for Step Definitions for UI Automation
  Cookbook/README.md
  Cookbook/Technical-Documents/UIAutomation.md
Labels: Ready for Review 🚀

#69 Add a few Q&As around how we work in the iOS team
  Cookbook/README.md
  Cookbook/Technical-Documents/WorkingAtBabylon.md
Labels: Ready for Review 🚀

#104 Add code review etiquette document
  Etiquette/CODE_REVIEW.md
  README.md
Labels: Ready for Review 🚀

#163 Update README.md
  README.md
Labels: Ready for Review 🚀

#160 Update FastlaneMatch.md
  Cookbook/README.md
  Cookbook/Technical-Documents/FastlaneMatch.md
Labels: Ready for Review 🚀

#161 Update release document for 4.0.0
  Cookbook/Technical-Documents/ReleaseProcess.md
Labels: Ready for Review 🚀

#162 Remove UIFlow from the list of OSS projects
  README.md
Labels: Ready for Review 🚀

#86 Created `Current-guide.md`
  Cookbook/README.md
  Cookbook/Technical-Documents/Current-guide.md
Labels: Ready for Review 🚀
