Repository babylonhealth/ios-playbook, pull requests merged in 2019-08, with the labels that each got.

#206 Update the preferred way to search XCUIElements
  Cookbook/Technical-Documents/AutomationIdentifiers.md
Labels: Ready for Review 🚀, Trivial

#209 [CNSMR-2303] Add documentation for Danger rules
  Cookbook/README.md
  Cookbook/Technical-Documents/DangerRules.md
Labels: Ready for Review 🚀

#187 Adopt SwiftGen for localizable strings
  Cookbook/Proposals/SwiftGen.md
Labels: Proposal 🙈, Ready for Review 🚀

#212 Added Daniel Spindelbauer to the team 🎉
  README.md
Labels: Ready for Review 🚀

#197 [CNSMR-1890] Smarter diffs in view models unit tests
  Cookbook/Proposals/SmarterDiffs.md
Labels: Proposal 🙈, Ready for Review 🚀

#214 Release 4.4.0
  Cookbook/Technical-Documents/ReleaseProcess.md
Labels: Ready for Review 🚀, Release 💥, Trivial

#210 Documentation - How to label a Pull Request
  Cookbook/README.md
  Cookbook/Technical-Documents/LabelsInPRs.md
Labels: Ready for Review 🚀

#215 Update squads and names
  README.md
Labels: Ready for Review 🚀

#184 Add some more advanced cases to the doc on creating a “backend” feature
  Cookbook/Technical-Documents/BackendFeatureHowTo.md
Labels: Ready for Review 🚀

#217 Update the Danger Rules doc for babylon-ios#8571
  Cookbook/Technical-Documents/DangerRules.md
Labels: Ready for Review 🚀

#192 Update Technical Debt Document.
  Cookbook/Technical-Documents/TechnicalDebt.md
Labels: Ready for Review 🚀

#221 Suggested updates for on boarding
  Cookbook/Technical-Documents/NewHiresCheckList.md
  Cookbook/Technical-Documents/ToolsAndServices.md
  scripts/ios-onboarding
Labels: Ready for Review 🚀

#223 Update monitor squads
  README.md
Labels: Ready for Review 🚀

#224 Add Daniel Haight to iOS team and update formatting on a couple of lines
  README.md
Labels: Ready for Review 🚀, Trivial

#179 CNSMR-1958 Testing Conventions Automating a flow
  Cookbook/Technical-Documents/AutomateAUIFlow.md
Labels: Ready for Review 🚀

#227 Update release calendar for Babylon 4.5.0
  Cookbook/Technical-Documents/ReleaseProcess.md
Labels: Ready for Review 🚀, Release 💥

#225 Refactor how the team info is displayed
  README.md
  scripts/squads.rb
  scripts/squads.yml
Labels: Ready for Review 🚀
