Repository babylonhealth/ios-playbook, pull requests merged in 2019-07, with the labels that each got.

#158 [CNSMR-2044] Update Release Process for uniformisation of branches & tags
  Cookbook/Technical-Documents/ReleaseProcess.md
Labels: Ready for Review 🚀

#168 Updates calendar table for 4.1.0
  Cookbook/Technical-Documents/ReleaseProcess.md
Labels: Ready for Review 🚀

#169 Rephrase dependency injection-inversion questions to make them clearer
  Interview/questions.md
Labels: Ready for Review 🚀

#173 Update ReleaseProcess.md
  Cookbook/Technical-Documents/ReleaseProcess.md
Labels: Ready for Review 🚀, Trivial

#166 First pass on creating a feature that works with the backend
  Cookbook/README.md
  Cookbook/Technical-Documents/BackendFeatureHowTo.md
Labels: Ready for Review 🚀

#175 Release engineer bug fixing scope
  Cookbook/Technical-Documents/ReleaseProcess.md
Labels: Proposal 🙈

#178 [Update] Update README.md
  README.md
Labels: Ready for Review 🚀

#183 Updated 'Monitor' and 'Tests and Kits' squads members
  README.md
Labels: Ready for Review 🚀

#153 [Proposal] Additional rules for Danger and SwiftLint
  Cookbook/Proposals/AdditionalRulesForDanger.md
Labels: Proposal 🙈, Ready for Review 🚀

#188 Fix typo
  Cookbook/Technical-Documents/SnowplowHowTo.md
Labels: Ready for Review 🚀, Trivial

#191 Life is made of changes isn't it?
  README.md
Labels: Ready for Review 🚀

#181 Updated calendar with times for 4.2.0 release
  Cookbook/Technical-Documents/ReleaseProcess.md
Labels: Ready for Review 🚀

#193 Never settle
  README.md
Labels: Ready for Review 🚀

#180 Describe using `AccessibilityContent` for elements and screens
  Cookbook/Technical-Documents/AutomationIdentifiers.md
Labels: Ready for Review 🚀

#176 [CNSMR-2107] Create UnitTestingViewModels.md
  Cookbook/README.md
  Cookbook/Technical-Documents/UnitTestingViewModels.md
Labels: Ready for Review 🚀

#195 [CNSMR-2324] Documentation to configure Pull Assigners
  Cookbook/Technical-Documents/PullAssigners.md
Labels: Ready for Review 🚀

#198 Added James Birtwell to team list, and E&I squad
  README.md
Labels: Ready for Review 🚀

#203 Update release page with times and details of 4.3.0
  Cookbook/Technical-Documents/ReleaseProcess.md
Labels: Ready for Review 🚀

#201 Add PullAssigner doc in README + mention limitation about team auto-removal
  Cookbook/README.md
  Cookbook/Technical-Documents/PullAssigners.md
Labels: Ready for Review 🚀, Trivial
