Repository babylonhealth/ios-playbook, pull requests merged in 2019-02, with the labels that each got.

#33 Details for the 3.9.0 release
  release.md
Labels: Ready for Review 🚀, Release 💥

#32 Changes in the proposal template + meeting template
  TechnicalDocuments/Proposals/Template_Proposal.md
  TechnicalDocuments/Proposals/Template_Proposal_Meeting_Invitation.md
Labels: Ready for Review 🚀

#30 Babylon Design Library
  TechnicalDocuments/Proposals/BabylonDesignLibrary.md
Labels: Ready for Review 🚀

#40 Details for 3.9.1 release
  release.md
Labels: Ready for Review 🚀

#31 Added document to details how we find XCUIElments in automation
  TechnicalDocuments/AutomationIdentifiers.md
Labels: Proposal 🙈, Ready for Review 🚀

#42 [nit] Fixes a quotes mistake - typo and tab formatting
  TechnicalDocuments/Lokalise.md
Labels: Ready for Review 🚀

#43 Remove CHANGELOG.md, cleanup README
  CHANGELOG.md
  README.md
Labels: Ready for Review 🚀

#41 How to Post and Test Snowplow Analytics Events.
  TechnicalDocuments/README.md
  TechnicalDocuments/SnowplowHowTo.md
Labels: Ready for Review 🚀

#36 Create an Inventory of Known Technical Debt and Legacy Code.
  TechnicalDocuments/BBAddAdditionalPatientInformationViewControllerV2.md
  TechnicalDocuments/README.md
  TechnicalDocuments/TechnicalDebt.md
Labels: Ready for Review 🚀

#38 Introduce fish operator (aka Kleisli composition)
  TechnicalDocuments/Proposals/Fish_Operator.md
Labels: Proposal 🙈
