Repository babylonhealth/ios-playbook, pull requests merged in 2020-04, with the labels that each got.

#367 [Danger Rules] Documentation for #11280
  Cookbook/Technical-Documents/DangerRules.md
Labels: Ready for Review 🚀

#368 Update ToolsAndServices.md
  Cookbook/Technical-Documents/ToolsAndServices.md
Labels: Ready for Review 🚀, Trivial

#342 Property wrappers for custom decoding
  Cookbook/Proposals/PropertyWrappers.md
Labels: Proposal 🙈

#373 Update release documentation
  Cookbook/Technical-Documents/ReleaseProcess.md
Labels: Ready for Review 🚀

#374 Updated CODE_REVIEW.md
  Etiquette/CODE_REVIEW.md
Labels: Ready for Review 🚀, Trivial

#375 Danger: add link to slides
  Cookbook/Technical-Documents/DangerRules.md
Labels: Ready for Review 🚀, Trivial

#370 [CNSMR-3521] Update the Release Process
  Cookbook/Technical-Documents/ReleaseProcess.md
Labels: Ready for Review 🚀

#377 [CNSMR-3521] Update the Release Process - Take 2
  Cookbook/Technical-Documents/ReleaseProcess.md
Labels: Ready for Review 🚀

#378 [IOSP-647] Add documentation for Danger HealthKit rule
  Cookbook/Technical-Documents/DangerRules.md
Labels: Ready for Review 🚀, Trivial
