Repository babylonhealth/ios-playbook, pull requests merged in 2020-03, with the labels that each got.

#351 Update tools and services
  Cookbook/Technical-Documents/NewHiresCheckList.md
  Cookbook/Technical-Documents/ToolsAndServices.md
Labels: Ready for Review 🚀, Trivial

#352 [IOSP-607] Update CODEOWNERS file to invite the ios-dev team for reviews
  CODEOWNERS
Labels: Ready for Review 🚀, Trivial

#353 Add sprint's notice warning to a squad
  Cookbook/Technical-Documents/ReleaseProcess.md
Labels: Ready for Review 🚀, Trivial

#354 Add week's notice warning
  Cookbook/Technical-Documents/SupportEngineerRole.md
Labels: Ready for Review 🚀, Trivial

#356 😭
  Cookbook/README.md
Labels: Ready for Review 🚀, Trivial

#355 Update WFH notification guidelines
  Cookbook/Technical-Documents/OutOffOfficeRequest.md
Labels: Ready for Review 🚀, Trivial

#357 4.17.0 release
  Cookbook/Technical-Documents/ReleaseProcess.md
Labels: Ready for Review 🚀, Release 💥

#358 [IOSP-393] Update Release Process w/ new lanes
  Cookbook/Technical-Documents/ReleaseProcess.md
Labels: Ready for Review 🚀

#360 Update doc about lokalise
  Cookbook/Technical-Documents/Lokalise.md
Labels: Ready for Review 🚀

#361 Update SupportEngineerRole.md
  Cookbook/Technical-Documents/SupportEngineerRole.md
Labels: Ready for Review 🚀, Trivial

#362 Update App Center doc
  Cookbook/Technical-Documents/AppCenter.md
Labels: Ready for Review 🚀

#359 [IOSP-607] Update PullAssigners document to remove reference to Pull Panda and explain GitHub's code review assignment
  Cookbook/Technical-Documents/Development-Process.md
  Cookbook/Technical-Documents/NewHiresCheckList.md
  Cookbook/Technical-Documents/OutOffOfficeRequest.md
  Cookbook/Technical-Documents/PullAssigners.md
  Cookbook/Technical-Documents/ToolsAndServices.md
  Etiquette/CODE_REVIEW.md
Labels: Ready for Review 🚀

#363 [IOSP-622] Update DangerRules.md with new SDK rules
  Cookbook/Technical-Documents/DangerRules.md
Labels: Ready for Review 🚀

#365 Added myself to the team and fixed a broken link to the slack guide
  Cookbook/README.md
  Cookbook/Technical-Documents/HowToUseSlack.md
  README.md
  scripts/squads.yml
Labels: Ready for Review 🚀

#364 add US specifics to release process
  Cookbook/Technical-Documents/ReleaseProcess.md
Labels: Ready for Review 🚀
