Repository babylonhealth/ios-playbook, pull requests merged in 2020-02, with the labels that each got.

#337 Update ReleaseProcess for SDK release
  Cookbook/Technical-Documents/ReleaseProcess.md
Labels: Ready for Review 🚀

#331 Update Release Process doc for new CRP automation
  Cookbook/Technical-Documents/ReleaseProcess.md
Labels: Ready for Review 🚀, Trivial

#336 Adds documentation for icons assets SwiftGen integration
  Cookbook/README.md
  Cookbook/Technical-Documents/SwiftGen.md
Labels: Ready for Review 🚀

#339 Update SwiftGen.md
  Cookbook/Technical-Documents/SwiftGen.md
Labels: Ready for Review 🚀, Trivial

#338 Added CircleCI config path to Slack CI Integration doc
  Cookbook/Technical-Documents/SlackCIIntegration.md
Labels: Ready for Review 🚀, Trivial

#341 Update release process document
  Cookbook/Technical-Documents/ReleaseProcess.md
Labels: Ready for Review 🚀

#346 Adds 4.16.0 time tracking
  Cookbook/Technical-Documents/ReleaseProcess.md
Labels: Ready for Review 🚀, Release 💥

#345 Update SDK release process
  Cookbook/Technical-Documents/ReleaseProcess.md
Labels: Ready for Review 🚀, Trivial

#340 Add info about how frameworks need to be Embed
  Cookbook/Technical-Documents/AddingFrameworks.md
Labels: Ready for Review 🚀, Trivial

#347 Update squads and members
  README.md
  scripts/squads.yml
Labels: Ready for Review 🚀

#312 [CNSMR-3278] How to use Slack
  Cookbook/Technical-Documents/Assets/onboarding/slack-notification-muted.png
  Cookbook/Technical-Documents/Assets/onboarding/slack-notification-preferences.png
  Cookbook/Technical-Documents/How to use Slack?.md
Labels: Ready for Review 🚀

#348 [Documentation] Add link to Slack document
  Cookbook/README.md
Labels: Ready for Review 🚀

#349 [Documentation] Fix Slack file name and linking
  Cookbook/README.md
  Cookbook/Technical-Documents/HowToUseSlack?.md
Labels: Ready for Review 🚀

#350 [IOSP-593] Update Danger documentation with new rules [check_absolute_paths] [swiftlint]
  Cookbook/Technical-Documents/DangerRules.md
Labels: Ready for Review 🚀, Trivial

#344 Add 4.14.0 and 4.14.1 time tracking
  Cookbook/Technical-Documents/ReleaseProcess.md
Labels: Ready for Review 🚀
