Repository babylonhealth/ios-playbook, pull requests merged in 2020-01, with the labels that each got.

#310 Update AddingFrameworks.md
  Cookbook/Technical-Documents/AddingFrameworks.md
Labels: Ready for Review 🚀, Trivial

#298 Update ReleaseProcess.md
  Cookbook/Technical-Documents/ReleaseProcess.md
Labels: Ready for Review 🚀

#306 [CNSMR-3232]added external libraries policy
  Cookbook/README.md
  Cookbook/Technical-Documents/External-libraries.md
Labels: Ready for Review 🚀

#301 [CNSMR-3254] Playbook fresh new look
  Cookbook/README.md
  README.md
  scripts/squads.yml
Labels: Ready for Review 🚀

#299 [CNSMR-3229] Add development process
  Cookbook/README.md
  Cookbook/Technical-Documents/Development-Process.md
Labels: Ready for Review 🚀

#311 [CNSMR-3230] Create article about JIRA
  Cookbook/Technical-Documents/JIRA.md
Labels: Ready for Review 🚀

#317 Update ReleaseProcess.md
  Cookbook/Technical-Documents/ReleaseProcess.md
Labels: Release 💥

#315 Update README.md
  Cookbook/README.md
Labels: Ready for Review 🚀, Trivial

#316 Fix another typo
  Cookbook/Technical-Documents/meetings-purpose.md
Labels: Ready for Review 🚀, Trivial

#174 [CNSMR-1991] How to deal with Localizations
  Cookbook/Technical-Documents/Assets/Localizations-appLanguages-buildSettings-userDefined.png
  Cookbook/Technical-Documents/Assets/Localizations-createFile.png
  Cookbook/Technical-Documents/Localizations.md
Labels: Ready for Review 🚀

#319 Signing off 👋
  README.md
  scripts/squads.yml
Labels: Ready for Review 🚀, Release 💥, Trivial

#313 [IOSP-514] [CNSMR-3272] Add detailed documentation about the CRP bot
  Cookbook/README.md
  Cookbook/Technical-Documents/CRP-Bot-ImplementationDetails.md
  Cookbook/Technical-Documents/CRP-Bot.md
Labels: Ready for Review 🚀

#314 [CNSMR-3228] Handling deep links
  Cookbook/README.md
  Cookbook/Technical-Documents/DeepLinks.md
Labels: Ready for Review 🚀

#322 Revert "[CNSMR-3228] Handling deep links (#314)"
  Cookbook/README.md
  Cookbook/Technical-Documents/DeepLinks.md
Labels: Ready for Review 🚀

#320 link to Localization document 😅
  Cookbook/README.md
Labels: Ready for Review 🚀, Release 💥

#324 [CNSMR-3226] - Application Distribution reversion
  Cookbook/Technical-Documents/ApplicationDistribution.md
Labels: Ready for Review 🚀, Trivial

#323 [CNSMR-3272] [IOSP-514] Moving doc about CRP Bot from playbook to private doc
  Cookbook/README.md
  Cookbook/Technical-Documents/CRP-Bot-ImplementationDetails.md
  Cookbook/Technical-Documents/CRP-Bot.md
Labels: Ready for Review 🚀

#325 [CE-1109] Appointments 2 squad update
  README.md
  scripts/squads.yml
Labels: Trivial

#327 Update ReleaseProcess.md with information about Export Compliance Information
  Cookbook/Technical-Documents/ReleaseProcess.md
Labels: Ready for Review 🚀

#328 Add detail about `optimizely-develop.json` / `optimizely-release.json`
  Cookbook/Technical-Documents/Optimizely.md
Labels: Ready for Review 🚀

#329 Fix ambiguity in Hotifx label description
  Cookbook/Technical-Documents/LabelsInPRs.md
Labels: Ready for Review 🚀, Trivial

#330 Update Optimizely.md to say that we can use SSO now
  Cookbook/Technical-Documents/Optimizely.md
Labels: Ready for Review 🚀

#332 Update release schedule for 4.15.0
  Cookbook/Technical-Documents/ReleaseProcess.md
Labels: Ready for Review 🚀

#333 [IOSP-515] [CNSMR-3231] Fix MergeBot link to link to WallE
  Cookbook/README.md
Labels: Ready for Review 🚀, Trivial

#334 PR automatically assigned to their creators
  Cookbook/Technical-Documents/Development-Process.md
Labels: Ready for Review 🚀, Trivial
