Repository babylonhealth/ios-playbook, pull requests merged in 2020-10, with the labels that each got.

#403 🗿 give me a t shirt hacktoberfest
  README.md
  scripts/squads.yml
Labels: hacktoberfest-accepted

#402 Updated access to services
  Cookbook/Technical-Documents/ToolsAndServices.md
Labels: Ready for Review 🚀, Trivial, hacktoberfest-accepted

#207 [CNSMR-2090] Conducting a Technical Interview.
  Interview/ConductingATechnicalInterview.md
Labels: Ready for Review 🚀

#405 Updated OSS owners
  Cookbook/README.md
Labels: Trivial, hacktoberfest-accepted
